root = "."
testdatadir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
pre_cmd = ["~/go/bin/templ generate", "sqlc generate"]
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = ["db/db.go", "db/models.go", "db/query.sql.go"]
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ", "sql"]
killdelay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clear_on_exit = false

[screen]
clear_on_rebuild = false