// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Bid struct {
	ID        int64
	Amount    float64
	UserID    int64
	ListingID int64
	OwnerName string
	CreatedAt sql.NullTime
}

type Category struct {
	ID    int64
	Title string
}

type Comment struct {
	ID        int64
	ListingID int64
	OwnerID   int64
	OwnerName string
	Comment   string
	CreatedAt sql.NullTime
}

type Listing struct {
	ID            int64
	Title         string
	StartingPrice float64
	Description   sql.NullString
	ImageUrl      string
	Active        sql.NullBool
	CreatedAt     sql.NullTime
	OwnerID       int64
	CategoryID    sql.NullInt64
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type User struct {
	ID       int64
	Username string
	Password string
}

type Watchlist struct {
	UserID    int64
	ListingID int64
	CreatedAt sql.NullTime
}
